Feature/snackbar
HOMIES-Project/homies-android pull request #12
Opened 2022-03-25 15:33 UTC by vramosm

## Description

Add snackBar
Add underline button

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

2022-03-26 14:54 UTC, cgutierr-zgz commented on app/src/main/java/com/homies/homies/user/RegisterFragment.java
> +    public void snackBar () {
Ponle un nombre más claro a la función como showSnackbar o algo del estilo

2022-03-26 14:55 UTC, cgutierr-zgz commented on app/src/main/res/values/strings.xml
> +    <string name="snack">Revisa tu email para finalizar el registro</string>
Al igual aquí y en el error de arriba, pondría claramente en el name el tipo de error o snack que pretendes que se muestre, asi se entiende mas claro al leer el código por ejemplo `snackbar_review_email`o yo que sé algo del estilo

2022-03-26 14:56 UTC, cgutierr-zgz requested changes
Revisa los comentarios pls

2022-03-27 00:45 UTC, cgutierr-zgz approved these changes

2022-03-27 07:41 UTC, merged

2022-03-27 07:49 UTC, vramosm commented
> 

Ya hice los cambios indicados, cambiando las nomenclatura confusas. Estaré más atento a los .idea para que no se me vuelvan a colar. Gracias por la revisión